In [32]:
import pandas as pd
import numpy as np

import sklearn.tree as tree
import sklearn.model_selection as ms
import sklearn.ensemble as ens
import sklearn.metrics as met

In [33]:
df = pd.read_csv("C:\\Python (Jupyter)\\Data\\bank-additional-full.csv", sep=";")

df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [35]:
import sklearn.preprocessing as prep

def encode_nominal_columns(df):
  le = prep.LabelEncoder()
  for column in ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'poutcome']:
    df[column + '_code'] = le.fit_transform(df[column])
  return df

In [36]:
df = encode_nominal_columns(df)

In [37]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,job_code,marital_code,education_code,default_code,housing_code,loan_code,contact_code,month_code,day_of_week_code,poutcome_code
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,3,1,0,0,0,0,1,6,1,1
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,7,1,3,1,0,0,1,6,1,1
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,7,1,3,0,2,0,1,6,1,1
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,0,1,1,0,0,0,1,6,1,1
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,7,1,3,0,0,2,1,6,1,1

In [38]:
X = df.drop(columns=['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'poutcome', 'y'], axis=1)
y = df['y']

In [39]:
label_counts = df.iloc[:,14].value_counts()
print(label_counts)

poutcome
nonexistent    35563
failure         4252
success         1373
Name: count, dtype: int64

In [40]:
X_train, X_test, y_train, y_test = ms.train_test_split(X, y, test_size=0.2, random_state=42)

In [41]:
from sklearn import ensemble
model = ensemble.RandomForestClassifier(max_depth=None, min_samples_split=2, n_estimators=100)
model.fit(X_train, y_train)

RandomForestClassifier()

In [42]:
y_prediksi = model.predict(X_test)

In [43]:
print('Akurasi = ', met.accuracy_score(y_test, y_prediksi))
print(met.classification_report(y_test, y_prediksi))
print('Skor Kepentingan Fitur = ',model.feature_importances_)

Akurasi =  0.9132070890992959
              precision    recall  f1-score   support

          no       0.94      0.96      0.95      7303
         yes       0.65      0.52      0.58       935

    accuracy                           0.91      8238
   macro avg       0.79      0.74      0.76      8238
weighted avg       0.91      0.91      0.91      8238

Skor Kepentingan Fitur =  [0.09207105 0.31644832 0.04186236 0.03313791 0.01251942 0.02283387
 0.02258335 0.02732068 0.10618259 0.06945618 0.04752935 0.02382003
 0.04338886 0.00859432 0.0201133  0.01493494 0.01010486 0.01886578
 0.0406147  0.02761813]